### ISSUE TITLE
crash on x86

### ISSUE THREAD

**Issue by a1291762** [soynerdito/BlueSound#4]
I have a RAZR I. Has a x86 CPU. App crashes when I click the button. I have catlog and pulled this for you.

02-20 20:25:13.998 E/AndroidRuntime(8636): FATAL EXCEPTION: main
02-20 20:25:13.998 E/AndroidRuntime(8636): java.lang.IllegalStateException: Could not execute method of the activity
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.view.View$1.onClick(View.java:3598)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.view.View.performClick(View.java:4091)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.view.View$PerformClick.run(View.java:17036)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.os.Handler.handleCallback(Handler.java:615)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.os.Handler.dispatchMessage(Handler.java:92)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.os.Looper.loop(Looper.java:137)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.app.ActivityThread.main(ActivityThread.java:5031)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at java.lang.reflect.Method.invokeNative(Native Method)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at java.lang.reflect.Method.invoke(Method.java:511)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at dalvik.system.NativeStart.main(Native Method)
02-20 20:25:13.998 E/AndroidRuntime(8636): Caused by: java.lang.reflect.InvocationTargetException
02-20 20:25:13.998 E/AndroidRuntime(8636):  at java.lang.reflect.Method.invokeNative(Native Method)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at java.lang.reflect.Method.invoke(Method.java:511)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.view.View$1.onClick(View.java:3593)
02-20 20:25:13.998 E/AndroidRuntime(8636):  ... 11 more
02-20 20:25:13.998 E/AndroidRuntime(8636): Caused by: java.lang.SecurityException: Permission Denial: broadcastIntent() requesting a sticky broadcast from pid=8636, uid=10188 requires android.permission.BROADCAST_STICKY
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.os.Parcel.readException(Parcel.java:1425)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.os.Parcel.readException(Parcel.java:1379)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.media.IAudioService$Stub$Proxy.startBluetoothSco(IAudioService.java:1722)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at android.media.AudioManager.startBluetoothSco(AudioManager.java:1380)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at com.soyblue.bluesound.BluetoothManager.streamAudioStart(BluetoothManager.java:20)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at com.soyblue.bluesound.MainActivity.startAudio(MainActivity.java:84)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at com.soyblue.bluesound.MainActivity.toggleAudioStatus(MainActivity.java:94)
02-20 20:25:13.998 E/AndroidRuntime(8636):  at com.soyblue.bluesound.MainActivity.onStreamClick(MainActivity.java:99)
02-20 20:25:13.998 E/AndroidRuntime(8636):  ... 14 more
02-20 20:25:14.008 W/ActivityManager(383):   Force finishing activity com.soyblue.bluesound/.MainActivity

**Comment by a1291762** [comment]
Should have said... Android 4.1.2
 Rooted. Otherwise stock.

**Comment by soynerdito** [comment]
Are you running  the latest  version of the app? Should make no difference
but just to know. Open play store MyApps and if update is available it
should come up.

**Comment by a1291762** [comment]
I'm using the latest fdroid build. Reports as 1.2

**Comment by soynerdito** [comment]
Application has been updated on the play store, apk also available here at https://github.com/soynerdito/BlueSound/tree/master/ReleaseBuild

**Comment by a1291762** [comment]
On 21/02/15 7:03 PM, Soynerdito wrote:

> Application has been updated on the play store, apk also available 
> here at https://github.com/soynerdito/BlueSound/tree/master/ReleaseBuild

This one doesn't crash.

Do you control the f-droid build or is someone else responsible for 
updating that?
I see that today there's a new build there that also doesn't crash but 
it still identifies as 1.2.

## 

Link

**Comment by soynerdito** [comment]
It doesn't crash, but is it working?

I have no control for f-droid. I didn't put it out there. It is cool to be posted there but I have no idea how it got there and how often it is updated. My master branch in github not always is production-ready code. I may need to create a development branch to avoid any later problem. Will try to remember to update the built apk here whenever I post a new one to google play.

**Comment by a1291762** [comment]
> It doesn't crash, but is it working?

No :( for both your all and the f-droid one.

> I have no control for f-droid.

That's a bit of a concern. I only found this app because it popped up on
f-droid. I tried it out because I haven't had much luck with Bluetooth on
this phone. It likes to stop working when I try to take a call in the car.
I've also had no luck getting more than calls through my headset.

I guess it's just something about this phone.

**Comment by unforgettableid** [comment]
All software available from the F-Droid folks is compiled by the F-Droid folks.  If their stuff is outdated, or if their software carries a wrong version number, feel free to report it in [the correct issue tracker](https://f-droid.org/issues/).

Unfortunately, I'm not one of the F-Droid staff.
